server:
  host: localhost
  port: 4444
  username: znc-user
  pass: znc-password
  nick: bot
  realname: Braindead bot
  ## specify bindhost to connect from a specified network interface
  # bindhost: my-cool-domain.example.org
  ## timeout for establishing connection, default 10 seconds (plus a few)
  # timeout: 10

bot:
  # prefix for commands -> ".foo" and "!foo" works
  command_prefix: !ruby/regexp /[.!]/
